escape_special_characters: 0
commit_message: '[ci skip]'
files:
  - source: /presentation/src/main/res/values/strings.xml
    translation: /presentation/src/main/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        sr-CS: b+sr+Latn
