name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Get submodules
      run: git submodule init && git submodule update 
    - name: Build with Gradle
      run: ./gradlew assembleApkstoreDebug
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./build/*.apk
