name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Get submodules
      run: git submodule init && git submodule update 
    - name: Build with Gradle
      run: PCLOUD_CLIENT_ID_DEBUG=uIVcDmySfxb DROPBOX_API_KEY_DEBUG=bf16cwjfe0r54vr ONEDRIVE_API_KEY_DEBUG=b57c3880-c857-4588-b02e-5da3c5b2174c ONEDRIVE_API_REDIRCT_URI_DEBUG=msauth://org.cryptomator/%2FMI0AUvjnpgOvKXEd5IvIxLoDN0%3D ./gradlew assembleApkstoreDebug
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: presentation/build/outputs/apk/apkstore/debug/presentation-apkstore-debug.apk
